### ISSUE TITLE
T in eval_faust.py 

### ISSUE THREAD

**Issue by asharmafr** [LIX-shape-analysis/GeomFmaps#1]
what is T here in this line of code? not defined above in code.

ind21 = np.ravel_multi_index(ind21.T, dims = [n_s, n_s])

**Comment by asharmafr** [comment]
also, what is errs_ref in the code? thank you for reply.

**Comment by nicolasdonati** [comment]
In numpy, A.T is the shortcut for the transposed of A, if A is a two dimensional matrix.
errs_ref stores the geodesic errors for the refined matches. Refinement is a post processing method described more thoroughly in our paper (section 4.6).
