### ISSUE TITLE
readOFF in eval_scripts

### ISSUE THREAD

**Issue by zss1995** [LIX-shape-analysis/GeomFmaps#2]
There are some "readOFF" functions in eval_scripts(eval_faust.py, eval_sherec.py,etc.)，without definition, are they the matlab code "readOff.m" in MATLAB_Tools/Utils/ ? Do we need to build a bridge between matlab and python?

**Comment by zjisuccess** [comment]
Hi,what you say  is defined in the off.py, try to check again,as i know, the readoff function has been defined by python setting.
In addition,you can build connection between matlab and python for specific goals,existing libs can be done.Of course,this behavior is not necessary. 
This is my view,and may not be correct,just to convey my idea for it.
Another thing,may be the meshplot module is losing in the viz module under eval_scripts.

**Comment by zss1995** [comment]
> Hi,what you say  is defined in the off.py, try to check again,as i know, the readoff function has been defined by python setting.
> In addition,you can build connection between matlab and python for specific goals,existing libs can be done.Of course,this behavior is not necessary.
> This is my view,and may not be correct,just to convey my idea for it.
> Another thing,may be the meshplot module is losing in the viz module under eval_scripts.

Thank you so much !
