### ISSUE TITLE
Distance matrix generation code

### ISSUE THREAD

**Issue by zss1995** [LIX-shape-analysis/GeomFmaps#3]
I cannnot find the distance matrix generation code, while in the eval code, the geodesic distance matrix is in need.

**Comment by nicolasdonati** [comment]
I will upload some code about how to get geodesic distance matrices shortly, which are used in the eval codes. If you want to get approximative results, you can use good old Euclidean distance :)

**Comment by nicolasdonati** [comment]
I will upload some code about how to get geodesic distance matrices shortly, which are used in the eval codes. If you want to get approximative results, you can use good old Euclidean distance :)

**Comment by caijinana** [comment]
Hello ,Have you slove the problem?I get the error ModuleNotFoundError: No module named 'utils.metrics'
