### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by shmily912** [LIX-shape-analysis/GeomFmaps#6]
Dear professor，sorry to bother you again，thanks for your great contribution,when i run the code, i met some issues, hope you can give me help.
1、How to obtain the geodesic distance matrix in the process of evaluation in your pipline，in addition，what is the mean of the value of "Gamma" and "SQRarea" in the specific mat file?
2、when i run the script eval_faust.py, this errro occurs : ModuleNotFoundError:No module named 'meshplot' ,which I can not find and solve.   
looking forword to you reply.

**Comment by dvirginz** [comment]
1. - I'll be happy to understand that as well

thanks.

**Comment by nicolasdonati** [comment]
Hi !
geodesic distance matrices are obtained by computing geodesic distance between pair of points of the mesh. you can find some code for this for example in https://github.com/orlitany/DeepFunctionalMaps

meshplot can simply be installed with conda. (conda install -c conda-forge meshplot)
This code does not require it though, I forgot to take out the import though sorry for this

**Comment by dvirginz** [comment]
Thanks for the response:)
The question is about `MAT_s['SQRarea'][0]`, a parameter I couldn't find a reference to in FMnet or here.
The question is how do you factor the pairwise geodesic distance matrix in the evaluation matrix? (e.g for fmnet it's `avg/max(D)`)

**Comment by nicolasdonati** [comment]
SQ_area is the square area of the mesh, which is used instead of max(D) (square area is considered more stable)
