### ISSUE TITLE
About Scape dataset Visualization.

### ISSUE THREAD

**Issue by cainiaoshidai** [LIX-shape-analysis/GeomFmaps#9]
Dear  professor，
     
I have got the matches about SCAPE dataset, but now I can't Visualization the result. Because I don't know how to use the file of .vts to calculate p2p ground-truth. Could you help me. Thank you.

Best

**Comment by nicolasdonati** [comment]
Hi, thanks for the interest,
The {meshxxx}.vts files each store a map from a template shape (with 5k samples) to the meshxxx.off shape.
To compute p2p ground truth one can for instance compute the k x k  ground truth functional map between X and Y
Cgt = np.linalg.pinv(X.evecs[X.vts, :k]) @ Y.evecs[Y.vts, :k]
And then retrieve a very good approximation of the ground truth point wise map from the ground truth fmap:
Tgt = NN(Cgt @ Y.evecs[:, :k], X.evecs[:, :k])
